### ISSUE TITLE
String vs dot object notation

### ISSUE THREAD

**Issue by nduckwiler** [JohnPhamous/codecademy-daily-journal#1]
In the below code, you access the `results` of the `json` object. Why use `json["results"]` instead of `json.results`? 

I ask because the dot notation is more common on Codecademy.

https://github.com/JohnPhamous/codecademy-daily-journal/blob/035902dc31d18b7eac02f1bb86167fde6937d307/src/api/unsplash/index.js#L7

**Comment by nduckwiler** [comment]
This is also used here:
https://github.com/JohnPhamous/codecademy-daily-journal/blob/035902dc31d18b7eac02f1bb86167fde6937d307/src/api/openWeatherMap/index.js#L8-L9

and here:
https://github.com/JohnPhamous/codecademy-daily-journal/blob/035902dc31d18b7eac02f1bb86167fde6937d307/src/api/quotes/index.js#L6-L11

**Comment by JohnPhamous** [comment]
@nduckwiler For consistency, I'll switch to dot.

This was a habit carried over from Typescript when field names have whitespace.
