### ISSUE TITLE
Learners don't know CSS import

### ISSUE THREAD

**Issue by nduckwiler** [JohnPhamous/codecademy-daily-journal#2]
Importing CSS isn't supported in our learning environment so this would be new to learners. It appears to be a popular pattern and it is used in `create-react-app` by deafult, so it would be useful for them to know.

https://github.com/JohnPhamous/codecademy-daily-journal/blob/035902dc31d18b7eac02f1bb86167fde6937d307/src/index.js#L3

Here are some options I can think of:
1. Don't explain it. `create-react-app` uses imported CSS by default, but they can just use stylesheets if they want.
2. Add an article that explains imported CSS and add it before the capstone project.
3. Add an "external" resource that links out to documentation. Add it before the capstone project.

**Comment by nduckwiler** [comment]
I think #2 is ideal and #3 is fine if we don't have time

**Comment by nduckwiler** [comment]
Another question that might come from this is: what about the challenge projects?

Those need to work both on- and off-platform, so they must use stylesheets (remember that imported CSS doesn't work in our environment). Thus we don't need to explain imported CSS before those challenge projects.

**Comment by benspector3** [comment]
Do we have an article that explains how to do challenge projects on platform? I imagine that this isn't the only limitation that would affect how they implement a project on-platform.

**Comment by nduckwiler** [comment]
@benspector3 Are you asking about (a) an article for learners, explaining how they do challenge projects on platform, or (b) an article for content contributors, explaining how to present challenge projects on platform?

If it's (a), we don't need it because the challenge projects use the project content type, and learners already know how to use these

**Comment by nduckwiler** [comment]
@JohnPhamous We already have a list of explanatory bullets we want to attach to the solution, including React Fragments and the unused `setCity`/`setState` actions. Let's add this to the list. (tell learners that the solution uses imported css, you can learn about it [insert link], it's okay to use stylesheets and classes)
