### ISSUE TITLE
No set city or set state feature

### ISSUE THREAD

**Issue by nduckwiler** [JohnPhamous/codecademy-daily-journal#3]
I'm noticing that the `setCity` and `setState` actions are defined for the `weatherSlice` but they are not used anywhere. In other words, a user of the app can't change the city or state.

This is okay–I'm just noting that. (@JohnPhamous you can close this when you've read it)

https://github.com/JohnPhamous/codecademy-daily-journal/blob/df09ff1ff8c6feaeea1de84834ce7f9f94bd8227/src/features/weather/weatherSlice.js#L17-L23

**Comment by JohnPhamous** [comment]
@nduckwiler Yup. The pattern for setting is expressed in the other slices. Thought I'd leave this one up to the learner to take and run.

If you think it's better for us to wire it up then happy to do it.

**Comment by nduckwiler** [comment]
No, let's leave the code as-is, but again, include a note for learners explaining this.
