### ISSUE TITLE
Learners don't know fragments

### ISSUE THREAD

**Issue by nduckwiler** [JohnPhamous/codecademy-daily-journal#4]
Similar to #2 , learners haven't been taught [React fragments](https://reactjs.org/docs/fragments.html#short-syntax). 

https://github.com/JohnPhamous/codecademy-daily-journal/blob/035902dc31d18b7eac02f1bb86167fde6937d307/src/features/journal/Journal.js#L23

We have some more options here:
1. Don't explain it. `create-react-app` doesn't use this by default, so they will only see it in this solution.
2. When linking to the solution, just note that this uses fragments, and link to documentation.
3. Replace this with something other than a fragment.
4. Add an article that explains fragments and add it before the capstone project.
5. Add an "external" resource that links out to documentation. Add it before the capstone project.

**Comment by nduckwiler** [comment]
I'm learning towards 2. It will be good for learners to understand this common practice but it isn't worth our efforts to write an article.

4 is also an option. Fragments alone aren't worth a whole informational, but it would be worth it if we throw imported CSS in there too.

**Comment by JohnPhamous** [comment]
@nduckwiler 2 or 4 works for me. Curious why we don't cover fragments? Jace's and Lily's project code also uses it. With n=3, I think we should cover it given that we all had use cases for it.

**Comment by benspector3** [comment]
I would agree with John. I would choose going with option 2 for now and consider adding fragments to the react content (or a potentially new "Advanced React Techniques" course).

**Comment by nduckwiler** [comment]
Noting here before I forget: Yes, I see that Jace and Lily use fragments in their challenge projects, but I'm assuming that they will need to replace those with div's with classes in order to get the proper styling.

Correct me if I'm wrong here. This is just a point to consider; haven't formed an opinion yet.

**Comment by nduckwiler** [comment]
Okay @JohnPhamous let's go with option 2
